spring:
  cloud:
    stream:
      function:
        definition : paymentProcessor
      bindings:
        paymentProcessor-in-0 :
          destination: orders-event
        paymentProcessor-out-0:
          destination: payment-event

server:
  port: 8082